Neos:
  Neos:
    fusion:
      autoInclude:
        'DRKTettnang.OperationHistory': TRUE
  Flow:
    security:
      authentication:
        providers:
          NeosBackendProvider:
            provider: 'PersistedUsernamePasswordProvider'
